In [2]:
# np.append(h,g) -Append items to an array
# np.insert(a, 1, 5) -Insert items in an array
# np.delete(a, [1]) -Delete items from an array          

In [4]:
import numpy as np
a = np.array([20, 40, 60, 80])
print(np.append(a, 90))

[20 40 60 80 90]


In [6]:
print(np.insert(a, 1, 69))

[20 69 40 60 80]


In [7]:
print(np.delete(a, 1))

[20 60 80]
