In [12]:
import numpy as np

a = [[30, 40, 30], [20, 40, 30]]
arr = np.array(a)
print(arr)
print(arr.shape)   # rows / columns
print(len(arr))   # number of nested values
print(np.size(arr)) #number of elements
print(type(arr))
print(arr.dtype)
print(arr.astype(int))

[[30 40 30]
 [20 40 30]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30 40 30]
 [20 40 30]]
