In [1]:
a = [30, 40, 50]
b = [5, 5, 3]
print(a + b)

[30, 40, 50, 5, 5, 3]


In [7]:
#concatenate
import numpy as np
arr1 = np.array([[30, 40], [50, 10]])
arr2 = np.array([[5, 5], [3, 2]])
print(np.concatenate([arr1, arr2]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  2]]


In [8]:
print(np.concatenate([arr1, arr2], axis = 1))

[[30 40  5  5]
 [50 10  3  2]]


In [10]:
print(np.hstack([arr1, arr2]))  #horizontal concatination

[[30 40  5  5]
 [50 10  3  2]]


In [12]:
print(np.vstack([arr1, arr2]))  #vertical concatination

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  2]]


In [15]:
a = np.array([20, 40, 30, 40, 10, 20])
print(np.array_split(a,3))

[array([20, 40]), array([30, 40]), array([10, 20])]
