In [2]:
import numpy as np

arr1= np.array([10, 30, 20, 10])
arr2= np.array([30, 20, 10, 20])
print(arr1 + arr2)
print(np.add(arr1, arr2))

[40 50 30 30]
[40 50 30 30]


In [4]:
import numpy as np

arr1= np.array([[30, 20], [10, 30]])
arr2= np.array([[30, 20], [10, 20]])
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[[ 0  0]
 [ 0 10]]
[[ 0  0]
 [ 0 10]]


In [6]:
import numpy as np

arr1= np.array([[30, 20], [10, 30]])
arr2= np.array([[30, 20], [10, 20]])
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[900 400]
 [100 600]]
[[900 400]
 [100 600]]


In [7]:
import numpy as np

arr1= np.array([[30, 20], [10, 30]])
arr2= np.array([[30, 20], [10, 20]])
print(arr1 / arr2)
print(np.divide(arr1, arr2))

[[1.  1. ]
 [1.  1.5]]
[[1.  1. ]
 [1.  1.5]]


In [12]:
arr1= np.array([3, 18, 69, 1])
arr2= np.array([2])
print(np.power(arr1, arr2))

[   9  324 4761    1]


In [13]:
arr1= np.array([9, 324, 4761, 1])
print(np.sqrt(arr1))

[ 3. 18. 69.  1.]
